{"name": "test_subtract", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 6\n  +5\n  -6", "trace": "def test_subtract():\n        result = subtract(8, 3)\n>       assert result == 6\nE       assert 5 == 6\nE         +5\nE         -6\n\ntest/test_subtract.py:5: AssertionError"}, "start": 1649661239914, "stop": 1649661239914, "uuid": "da05d67e-ebd0-45ab-99b9-42e6f2258b56", "historyId": "b0d7561a3f1874434ff428a4d0b7de66", "testCaseId": "ec01225943865df1294ae890163c6750", "fullName": "test.test_subtract#test_subtract", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_subtract"}, {"name": "host", "value": "jchong-desktop"}, {"name": "thread", "value": "127936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_subtract"}]}